### ISSUE TITLE
你好你这语音机器人点歌api是对接文档有吗

### ISSUE THREAD

**Issue by Xuzan9396** [Ink-33/SMLKBOT#3]

**Comment by Ink-33** [comment]
具体对接什么

**Comment by fkx4-p** [comment]
Please refer to [This file](https://github.com/Ink-33/SMLKBOT/blob/main/plugins/music/vtbmusic.go) and the [VTBMusic Project](https://gitee.com/mrams/vtb-music)

**Comment by Xuzan9396** [comment]
查歌曲名回复语音内容

**Comment by Xuzan9396** [comment]
@Ink-33

**Comment by Ink-33** [comment]
> 查歌曲名回复语音内容

这个bot并不支持这个功能呢
